server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/krish/spring-cloud-config
          search-paths:
           - '*service'

member:
 rent:
  min: 7
  max: 30
 price:
  discount: 3
vehicle:
 default:
  model: cross over
duration: all

